export const QUESTION_TYPE = 'EDITOR/QUESTION_TYPE';
export const RESET = 'EDITOR/RESET';

export const REQUEST_CONTENT = 'EDITOR/REQUEST_CONTENT';

export const RECEIVE_QUESTIONS = 'EDITOR/RECEIVE_QUESTIONS';
export const RECEIVE_PASSAGES = 'EDITOR/RECEIVE_PASSAGES';

export const RECEIVE_QUESTION = 'EDITOR/RECEIVE_QUESTION';
export const RECEIVE_PASSAGE = 'EDITOR/RECEIVE_PASSAGE';

export const POSTING_CONTENT = 'EDITOR/POSTING_CONTENT';