export const QUIZ_TYPE = 'QUIZ/CURRENT_QUIZ/QUIZ_TYPE';

export const CHANGE_IDX = 'QUIZ/CURRENT_QUIZ/CHANGE_IDX';
export const RESET = 'QUIZ/CURRENT_QUIZ/RESET';
export const USER_CHOICE = 'QUIZ/CURRENT_QUIZ/USER_CHOICE';
export const SUBMIT_QUIZ = 'QUIZ/CURRENT_QUIZ/SUBMIT_QUIZ';

export const REQUEST_CONTENT = 'QUIZ/CURRENT_QUIZ/REQUEST_CONTENT';

export const RECEIVE_QUESTIONS = 'QUIZ/CURRENT_QUIZ/RECEIVE_QUESTIONS';
export const RECEIVE_PASSAGES = 'QUIZ/CURRENT_QUIZ/RECEIVE_PASSAGES';
