export const CHANGE_IDX = 'QUIZ/CURRENT_QUIZ/CHANGE_IDX';
export const RESET = 'QUIZ/CURRENT_QUIZ/RESET';
export const USER_CHOICE = 'QUIZ/CURRENT_QUIZ/USER_CHOICE';
export const SUBMIT_QUIZ = 'QUIZ/CURRENT_QUIZ/SUBMIT_QUIZ';

export const REQUEST_QUESTIONS = 'QUIZ/CURRENT_QUIZ/REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'QUIZ/CURRENT_QUIZ/RECEIVE_QUESTIONS';

