export const LOGIN = 'LOGIN/LOGIN';
export const SIGN_UP = 'LOGIN/SIGN_UP';
export const LOGOUT = 'LOGIN/LOGOUT';

export const SIGNING_UP = 'LOGIN/SIGNING_UP';
export const LOGGING_IN = 'LOGIN/LOGGING_IN';

export const SET_TOKEN = 'LOGIN/SET_TOKEN';

export const SET_LOGIN_NOTIFICATION = 'LOGIN/SET_LOGIN_NOTIFICATION';
export const CLEAR_LOGIN_NOTIFICATION = 'LOGIN/CLEAR_LOGIN_NOTIFICATION';